version: "2.4"

services:
  domjudge-db:
    image: mariadb:10.11
    container_name: qoj-domjudge-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DOMJUDGE_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOMJUDGE_DB_NAME}
      MYSQL_USER: ${DOMJUDGE_DB_USER}
      MYSQL_PASSWORD: ${DOMJUDGE_DB_PASSWORD}
      TZ: ${CONTAINER_TIMEZONE}
    command:
      - --max-connections=1000
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - domjudge-db-data:/var/lib/mysql
    networks:
      - domjudge-net

  domserver:
    image: domjudge/domserver:latest
    container_name: qoj-domserver
    restart: unless-stopped
    depends_on:
      - domjudge-db
    ports:
      - "${DOMJUDGE_PORT}:80"
    environment:
      MYSQL_HOST: domjudge-db
      MYSQL_ROOT_PASSWORD: ${DOMJUDGE_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOMJUDGE_DB_NAME}
      MYSQL_USER: ${DOMJUDGE_DB_USER}
      MYSQL_PASSWORD: ${DOMJUDGE_DB_PASSWORD}
      CONTAINER_TIMEZONE: ${CONTAINER_TIMEZONE}
    volumes:
      - domjudge-domserver-data:/opt/domjudge/domserver
    networks:
      - domjudge-net

  judgehost:
    image: domjudge/judgehost:latest
    container_name: qoj-judgehost-0
    restart: unless-stopped
    depends_on:
      - domserver
    hostname: judgedaemon-0
    environment:
      DAEMON_ID: 0
      DOMSERVER_BASEURL: http://domserver/
      JUDGEDAEMON_PASSWORD: ${JUDGEDAEMON_PASSWORD}
      CONTAINER_TIMEZONE: ${CONTAINER_TIMEZONE}
    cap_add:
      - SYS_PTRACE
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - domjudge-net

volumes:
  domjudge-db-data:
  domjudge-domserver-data:

networks:
  domjudge-net:
    name: qoj-domjudge-net
